# Generated by Django 5.2.5 on 2025-09-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dummy_field',
            field=models.BooleanField(default=False),
        ),
    ]
