# Generated by Django 5.2.5 on 2025-09-30 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_dummy_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dummy_field',
        ),
    ]
