# Generated by Django 5.2.5 on 2025-09-04 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_read_book', 'Can read book'), ('can_edit_book', 'Can edit book'), ('can_delete_book', 'Can delete book')]},
        ),
    ]
