# posts/urls.py (Updated)
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import PostViewSet, CommentViewSet, FeedView # Ensure FeedView is imported

# Initialize the router for ViewSets
router = DefaultRouter()
# Route for /posts/ (e.g., /api/posts/ if included in the main project urls)
router.register(r'posts', PostViewSet)
# Route for /comments/
router.register(r'comments', CommentViewSet)

# Define urlpatterns
urlpatterns = [
    # New feed route: This will handle GET requests for the user's feed
    path('feed/', FeedView.as_view(), name='user_feed'),
    
    # Include all the ViewSet routes generated by the router
    # This must be included in the urlpatterns list using path('', include(router.urls))
    path('', include(router.urls)),
]