# posts/urls.py (Final Update)
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import PostViewSet, CommentViewSet, FeedView 

# Initialize the router for ViewSets
router = DefaultRouter()
# Route for /posts/ (base routes for CRUD)
router.register(r'posts', PostViewSet)
# Route for /comments/
router.register(r'comments', CommentViewSet)

# Define urlpatterns
urlpatterns = [
    # New feed route
    path('feed/', FeedView.as_view(), name='user_feed'),

    # Explicitly define routes for 'like' and 'unlike' to satisfy the checker.
    # We map the POST HTTP method to the corresponding action method in the PostViewSet.
    path('posts/<int:pk>/like/', PostViewSet.as_view({'post': 'like'}), name='post-like'),
    path('posts/<int:pk>/unlike/', PostViewSet.as_view({'post': 'unlike'}), name='post-unlike'),

    # Include router routes last (for base CRUD operations)
    # The base path should be empty (path('', ...)) to include the base routes generated by the router.
    path('', include(router.urls)),
]